/* ═══════════════════════════════════════════════════════════════
   직장인 꿀템 연구소 · 상품 목록
   ───────────────────────────────────────────────────────────────
   ✏️ 새 상품을 추가할 때는 아래 목록 맨 위에 한 덩어리만 복사해서 넣으세요.

   { no: 9,                                  ← 번호 (영상에서 "9번이요" 라고 말하는 그 번호)
     name: "제품 이름",                        ← 화면에 보이는 이름
     cat: "데스크",                            ← 데스크 / 수면 / 먹거리 / 돈관리 / 케어  중 하나
     desc: "한 줄 설명",                       ← 없어도 됨
     link: "https://link.coupang.com/a/XXXX", ← 쿠팡 파트너스 링크 (필수)
     video: "https://youtube.com/shorts/XXX", ← 소개한 쇼츠 (없으면 이 줄 삭제)
     img: "https://…",                        ← 상품 사진 (없으면 이 줄 삭제 · 번호 타일로 표시됨)
     plat: "토스쇼핑",                         ← 판매 플랫폼 (없으면 '쿠팡'으로 봅니다)
     hot: true },                             ← 인기 표시 (없으면 이 줄 삭제)

   ⚠️ 각 줄 끝의 쉼표(,)와 중괄호({ })를 지우지 마세요. 페이지가 안 열립니다.
   ═══════════════════════════════════════════════════════════════ */

window.PRODUCTS = [

  { no: 34,
    name: "전동 계단 리프트 접이식 운반차 (계단 오르는 전동카트)",
    cat: "공구",
    desc: "무거운 짐 싣고 버튼만 누르면 전동으로 계단을 오르내리는 운반차 · 평지에선 일반 카트처럼 · 냉장고·세탁기·이삿짐·물박스 운반 · 이사·택배·창고 필수 장비 · 360,990원 (12%, 2026-09-22 확인)",
    link: "https://link.coupang.com/a/hfqdNGogou",
    img: "cart34.png",
    hot: true },

  { no: 33,
    name: "라온 메탈 제트 플레임 휴대용 캠핑토치",
    cat: "여름",
    desc: "한 손에 쏙 들어오는 휴대용 제트 화염 토치 · 부탄가스만 꽂으면 끝 · 젖은 장작·숯불도 순식간에 점화 · 천 도 넘는 강력 화력 · 사방향 냉각 · 13,320원 (10%, 2026-09-22 확인)",
    link: "https://link.coupang.com/a/hfgrYqiq1Q",
    video: "https://youtube.com/shorts/7CxameEPbhE",
    img: "torch33.png",
    hot: true },

  { no: 32,
    name: "Klein Tools 마그네틱 와이어 풀러 키트 (9m 야광 낚싯대)",
    cat: "공구",
    desc: "벽 안 전선을 자석으로 슥 끌어당기는 프로용 배선 도구 · 벽 안 뜯을 필요 없이 원하는 자리로 · 9m 야광 낚싯대+자석 · 224,000원 (2026-09-20 확인)",
    link: "https://link.coupang.com/a/hb7KyGcQyy",
    video: "https://youtube.com/shorts/6EewS6vKE_o",
    img: "mag32.png",
    hot: true },

  { no: 31,
    name: "2핀 무탈피 전선 커넥터 전기선 연결잭 (100개)",
    cat: "공구",
    desc: "피복 안 벗기고 전선 넣고 펜치로 눌러 1분 연결 · 테이프 불필요 · T자 분기 가능 · 100개 19,200원(개당 192원, 2026-09-20 확인)",
    link: "https://link.coupang.com/a/hb51hkPSiO",
    video: "https://youtube.com/shorts/9n3FZX3imm4",
    img: "conn31.png",
    hot: true },

  { no: 30,
    name: "가빈 빅사이즈 편광 스포츠 선글라스 G30",
    cat: "여름",
    desc: "물속까지 훤히 보이는 편광 렌즈 · 눈부신 반사광 차단 · 자외선 99.99% 차단 · 낚시·운전·등산·캠핑 · 9가지 색상 · 23,900원 (2026-09-20 확인)",
    link: "https://link.coupang.com/a/hb36S3V9s4",
    video: "https://youtube.com/shorts/9UrE-0Tk9ao",
    img: "sun30.png",
    hot: true },

  { no: 29,
    name: "서윤픽 접이식 LED 캠핑 태양광 랜턴 5패널 축구공 랜턴",
    cat: "여름",
    desc: "축구공처럼 접었다 4면 활짝 펴지는 태양광 랜턴 · 콘센트 없이 햇빛 충전 · 5단계 밝기 · 걸이형 · 캠핑·낚시·정전 대비 · 23,000원 (2026-09-20 확인)",
    link: "https://link.coupang.com/a/hb1kkOFgxo",
    video: "https://youtube.com/shorts/rPElZt51TK8",
    img: "lamp29.png",
    hot: true },

  { no: 28,
    name: "조카리 자동형 와이어 스트립퍼 T20050",
    cat: "공구",
    desc: "전선 넣고 쥐면 피복이 알아서 벗겨지는 자동 탈피기 · 굵기 자동 맞춤 · 68,340원 (2026-09-20 확인)",
    link: "https://link.coupang.com/a/hbXbXDV5P3",
    video: "https://youtube.com/shorts/K4zrQMGSzlA",
    img: "strip28.png",
    hot: true },

  { no: 27,
    name: "디센느 자충매트 고속 자동충전 에어매트 확장형 캠핑 매트 5cm",
    cat: "차량",
    desc: "밸브만 열면 알아서 부풀어 두툼한 침대 · 차박·캠핑·손님용 · 5cm · 36,900원 (2026-09-20 확인)",
    link: "https://link.coupang.com/a/hbUIm7fMGG",
    video: "https://youtube.com/shorts/_zvi3aAE-6g",
    img: "mat27.png",
    hot: true },

  { no: 26,
    name: "슈즈 폼 클리너 운동화 세정제 신발클리너 간편 세척",
    cat: "케어",
    desc: "누렇게 찌든 운동화에 거품 바르고 문지르면 하얗게 · 11,300원 (2026-09-19 확인)",
    link: "https://link.coupang.com/a/g9860C1NYW",
    video: "https://youtube.com/shorts/qbSsb0xg9Gc",
    img: "shoefoam26.png",
    hot: true },

  { no: 25,
    name: "빨간금붕어 스핀탱크 배관 관통기 20m",
    cat: "공구",
    desc: "하수구·배관 막힘 뚫는 스프링 관통기 20m · 327,000원 (2026-09-04 확인) · 로켓배송",
    link: "https://link.coupang.com/a/gLCtdTtvzg",
    video: "https://youtube.com/shorts/A5rM4Ff7nQg",
    img: "radfish25.png",
    hot: true },

  { no: 24,
    name: "스마트폰 화면 확대기 (스크린 확대기)",
    cat: "부모님",
    desc: "접이식 스크린 확대기 · 거치대 열고 폰만 올리면 끝 · 높이 조절 · ⚠️ 확대라 화질이 좋아지진 않음",
    link: "https://link.coupang.com/a/gBqx2kPdRY",
    video: "https://youtube.com/shorts/9aOPNbGLjeg",
    img: "big24.png",
    hot: true },

  { no: 23,
    name: "Gelnaz 신발 전용 미니 세탁기",
    cat: "주방",
    desc: "통 안쪽 세척솔이 돌며 신발을 닦는 통돌이 · 한 번에 한두 켤레 · 세탁소 안 가고 집에서",
    link: "https://link.coupang.com/a/glr0S6YRrM",
    video: "https://youtube.com/shorts/ldZ_58zz3ZA",
    img: "shoes23.png",
    hot: true },

  { no: 22,
    name: "가정용 고압 스팀청소기",
    cat: "주방",
    desc: "물만 넣고 세제 없이 고온 스팀 · 가스레인지 기름때·수전 물때·창틀 · 노즐 여러 개 · ⚠️ 고온 화상 주의",
    link: "https://link.coupang.com/a/gjkKsb6vN6",
    video: "https://youtube.com/shorts/ceCXDtiedpc",
    img: "steam22.png",
    hot: true },

  { no: 21,
    name: "스피큘엑스 알라딘 해초 필링 오리진필 세트 (5종)",
    cat: "케어",
    desc: "해면 스피큘로 문지르는 홈필링 · 5종 세트 · ⚠️ 사용 후 약 36시간 따끔거림, 1주간 음주·직사광선 주의, 민감성 피부는 사전 테스트",
    link: "https://link.coupang.com/a/gjkKu6rHXg",
    video: "https://youtube.com/shorts/_iskDGFf0Xs",
    img: "peel21.png",
    hot: true },

  { no: 20,
    name: "무아스 멀티 육각 시계 타이머 2세대",
    cat: "데스크",
    desc: "굴려서 놓으면 시작 · 면마다 5/10/20/30분 · 시계 겸용 · 화이트/옐로우/민트/스카이",
    link: "https://link.coupang.com/a/gjkKxwRok0",
    video: "https://youtube.com/shorts/loXJ8bfN0NI",
    img: "timer20.png",
    hot: true },

  { no: 19,
    name: "아기 불가사리 극세사 침낭 (곰귀 후드)",
    cat: "육아",
    desc: "팔다리 쫙 벌어지는 별 모양 · 겉 알파카 벨벳 + 안 면직물 · 유모차 그대로 · 핑크/블루/그레이/카키",
    link: "https://link.coupang.com/a/gjkKAsuRHw",
    video: "https://youtube.com/shorts/1iZ7TkFF3aM",
    img: "baby19.png",
    hot: true },

  { no: 18,
    name: "풀페이스 스노클 마스크 + 0.5L 미니 산소통 세트",
    cat: "여름",
    desc: "얼굴 전체 덮는 마스크 + 펌프로 직접 충전 · 블랙/옐로우 · ⚠️ 0.5L는 수면 근처 수 분용, 깊이 잠수 금지",
    link: "https://link.coupang.com/a/gjkKC6QB0S",
    video: "https://youtube.com/shorts/OhK4KFnxwIQ",
    img: "scuba18.png",
    hot: true },

  { no: 17,
    name: "가스코 가죽컬러크림 15g",
    cat: "차량",
    desc: "까지고 벗겨진 가죽 메우는 크림 · 소파·차 시트·가방·구두 · 색상 28종",
    link: "https://link.coupang.com/a/gjkKFJeYiy",
    video: "https://youtube.com/shorts/eWMtvpbkAks",
    img: "leather17.png",
    hot: true },

  { no: 16,
    name: "Gaayou 스마트 차량 디퓨저",
    cat: "차량",
    desc: "타면 자동 작동 · 나노 미스트 + 컬러 무드등 · 차량/실내 겸용",
    link: "https://link.coupang.com/a/gjkKIdEK3E",
    video: "https://youtube.com/shorts/77LGLxqdqfk",
    img: "diffuser16.png",
    hot: true },

  { no: 14,
    name: "두꺼비집 가리개 마그네틱 자석 액자",
    cat: "집꾸미기",
    desc: "못생긴 배전함 가리고 굿즈·사진 전시대로 · 알루미늄 40x30",
    link: "https://link.coupang.com/a/gjkKMWyZps",
    video: "https://youtube.com/shorts/VxYNAPin6Iw",
    img: "board14.png",
    hot: true },

  { no: 13,
    name: "SALANGE USB 별하늘 프로젝터 무드등",
    cat: "수면",
    desc: "천장에 은하수·달·별자리 · 360도 회전 + 밝기조절 · USB",
    link: "https://link.coupang.com/a/gjkKPthm5Q",
    video: "https://youtube.com/shorts/txuOutlebCg",
    img: "star13.png",
    hot: true },

  { no: 12,
    name: "KBKXOZ 4in1 스마트 센서 블루투스 스피커",
    cat: "데스크",
    desc: "폰 올려놓으면 자동 재생 · 거치대+충전+RGB무드등 4in1",
    link: "https://link.coupang.com/a/gjkKSZ9OV2",
    video: "https://youtube.com/shorts/OuT7hSG_OdE",
    img: "spk12.png",
    hot: true },

  { no: 11,
    name: "아이스 선풍기 에어컨 쿨링 조끼 (공조복)",
    cat: "여름",
    desc: "등에 팬 2개 — 입는 에어컨, 여름 외근·현장 필수 · KC인증",
    link: "https://link.coupang.com/a/gjkKVpV63V",
    video: "https://youtube.com/shorts/9uVbqEORGnw",
    img: "vest-cool.png",
    hot: true },

  { no: 10,
    name: "트랙라인 전기 팻바이크 (자토바이)",
    cat: "출퇴근",
    desc: "지옥철 대신 출퇴근 대안 · 헬멧 필수, 구매 전 법규·스펙 꼭 확인",
    link: "https://link.coupang.com/a/gjkKXLAITY",
    img: "https://thumbnail.coupangcdn.com/thumbnails/remote/492x492ex/image/vendor_inventory/2e31/e093db0ea1621ee8b9a53128d823f8207a8f2edbcb98bf79760809f72046.png",
    hot: true },

  { no: 9,
    name: "애플 에어태그 2세대",
    cat: "육아",
    desc: "아이 가방에 쏙 — '나의 찾기' 앱으로 물건 위치 확인 (실시간 GPS 아님)",
    link: "https://link.coupang.com/a/gjkK0k4TTg",
    img: "https://thumbnail.coupangcdn.com/thumbnails/remote/q89/image/rs_quotation_api/slkcphbv/fc3d7a73ee79458e88db791150db5579.jpg",
    hot: true },

  { no: 8,
    name: "헤라 옴므 스킨·로션 2종 세트",
    cat: "케어",
    desc: "아침 5분, 세수하고 이것만 바르면 끝",
    link: "https://link.coupang.com/a/gjkK2FljXM" },

  { no: 7,
    name: "지클릭커 버티컬 마우스",
    cat: "데스크",
    desc: "손목이 꺾이지 않는 각도 — 하루 종일 마우스 잡는 분 필수",
    link: "https://link.coupang.com/a/gjkK4V8mtM",
    video: "https://youtube.com/shorts/5ITNMDMF_DU",
    hot: true },

  { no: 6,
    name: "씨앤초이스 저금통",
    cat: "돈관리",
    desc: "월급이 어디 갔는지 모를 때, 눈에 보이게 모으기",
    link: "https://link.coupang.com/a/gjkK7fdUAK",
    video: "https://youtube.com/shorts/XPAmimejZyA" },

  { no: 5,
    name: "켈로그 그래놀라",
    cat: "먹거리",
    desc: "아침에 5분도 없을 때 — 우유만 부으면 끝",
    link: "https://link.coupang.com/a/gjkK9EdBka",
    video: "https://youtube.com/shorts/8UBSvXZAZkE" },

  { no: 4,
    name: "스미후루 바나나",
    cat: "먹거리",
    desc: "출근길에 하나, 씻을 필요도 없는 아침",
    link: "https://link.coupang.com/a/gjkLb4lBfw",
    video: "https://youtube.com/shorts/8UBSvXZAZkE" },

  { no: 3,
    name: "제이제이 온열 안대",
    cat: "수면",
    desc: "하루 종일 모니터 본 눈, 자기 전 10분",
    link: "https://link.coupang.com/a/gjkLffR1Fs",
    video: "https://youtube.com/shorts/BrPptJE-t7s" },

  { no: 2,
    name: "홈플래닛 LED 무드등",
    cat: "수면",
    desc: "형광등 끄고 이것만 — 잠들기 전 셧다운 루틴",
    link: "https://link.coupang.com/a/gjkLihuSD6",
    video: "https://youtube.com/shorts/BrPptJE-t7s",
    hot: true },

  { no: 1,
    name: "아이시스 무라벨 생수 300ml",
    cat: "먹거리",
    desc: "책상에 올려두는 순간 물 마시는 양이 달라집니다",
    link: "https://link.coupang.com/a/gjkLkGwhVY",
    video: "https://youtube.com/shorts/grpgLWuri2c" }
];
